objects/Room__c/fields/Hotel_Name__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Name__c</fullName>
    <description>This field will contain the specified hotels name.</description>
    <label>Hotel Name</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/HotelRoomCreatorTrigger_Handler.cls
public with sharing class HotelRoomCreatorTrigger_Handler {
   
    public static void createRoomsToHotel(List<Hotel__c> hotels){
        
        List<Room__c> rooms = new List<Room__c>();
    
        for (Hotel__c hotel : hotels) {
                rooms.add(new Room__c (Type_of_Rooms__c = 'Standard Singel Room', 
                Price__c = 350,
                Hotel_Name__c = hotel.Id));
                rooms.add(new Room__c (Type_of_Rooms__c = 'Standard Double Room', 
                Price__c = 450,
                Hotel_Name__c = hotel.Id));    
        }
        if (rooms.size() > 0) {
            insert rooms;
        }
    }
}